### ISSUE TITLE
In VSIX Deploy Assembly add flag to optionally refresh all workflow activity input/outputs

### ISSUE THREAD

**Issue by josephmcmac** [josephmcmac/XRM-Developer-Tool#137]
Currently when the deploy assembly process is run if there are any custom workflow activities in the assembly then the process sets a field on the plugin type record for all those custom workflow activities which has the effect of the dynamics platform refreshing the input/output arguments

With this update there is a checkbox on the deploy assembly form. If it is not set then the plugin type record for the custom workflow activity will only be updated if values in the entry form have specifically changed. If the flag is set true it will update all them either way with intention to refresh input/output arguments which have changed in the assembly classes

**Comment by phuocle** [comment]
I'm looking the code for this. Could you help me show where in your repos. Thanks.

**Comment by josephmcmac** [comment]
> I'm looking the code for this. Could you help me show where in your repos. Thanks.

Hi @phuocle - I have linked what I think are the relevant changesets. Unfortunatelly I had not isolated and linked the change at the time for various reasons including that it got buried within a different change

As explained in the changeset comment setting the field "pluginassemblyid" on the "plugintype" record during an update message seems to trigger the platform to refresh the input/output arguments. This seems to work despite the "pluginassemblyid" not actually changing in this scenario

**Comment by phuocle** [comment]
I saw your comment

 //added this for plugin types where workflow activity
//do not update the in/out arguments
//explicitly setting the pluginassemblyid seems to refresh them
```c#
changedFields.Add(Fields.plugintype_.pluginassemblyid);
```

What does it mean for this case?

I'm ask you because I develop my own CLI that can update plugin, workflow, ... but for workflow I has a problem that I cannot update workflow when the In/Or arg changed.

Thanks for your help

**Comment by phuocle** [comment]
10x Thanks,

It work with my CLI now.

Yeah, a small tips but change a lot of work !!!!!!!
